/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *label146;
  GtkObject *spinbutton31_adj;
  GtkWidget *spinbutton31;
  GtkWidget *label148;
  GtkWidget *combobox12;
  GtkObject *spinbutton32_adj;
  GtkWidget *spinbutton32;
  GtkWidget *entry45;
  GtkWidget *label149;
  GtkWidget *label147;
  GtkWidget *label145;
  GtkWidget *entry46;
  GtkWidget *textview3;
  GtkWidget *button55;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label6;
  GtkWidget *label150;
  GtkWidget *combobox10;
  GtkWidget *combobox11;
  GtkWidget *button58;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  label146 = gtk_label_new (_("expedateur"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed1), label146, 24, 72);
  gtk_widget_set_size_request (label146, 96, 24);

  spinbutton31_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton31 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton31_adj), 1, 0);
  gtk_widget_show (spinbutton31);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton31, 360, 88);
  gtk_widget_set_size_request (spinbutton31, 60, 27);

  label148 = gtk_label_new (_("date"));
  gtk_widget_show (label148);
  gtk_fixed_put (GTK_FIXED (fixed1), label148, 288, 96);
  gtk_widget_set_size_request (label148, 64, 16);

  combobox12 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox12);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox12, 440, 88);
  gtk_widget_set_size_request (combobox12, 88, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("MAi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Octobre "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("Nobvembre "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox12), _("D\303\251cembre"));

  spinbutton32_adj = gtk_adjustment_new (1999, 1880, 2020, 1, 10, 10);
  spinbutton32 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton32_adj), 1, 0);
  gtk_widget_show (spinbutton32);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton32, 560, 96);
  gtk_widget_set_size_request (spinbutton32, 60, 27);

  entry45 = gtk_entry_new ();
  gtk_widget_show (entry45);
  gtk_fixed_put (GTK_FIXED (fixed1), entry45, 136, 224);
  gtk_widget_set_size_request (entry45, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry45), 8226);

  label149 = gtk_label_new (_("Objet"));
  gtk_widget_show (label149);
  gtk_fixed_put (GTK_FIXED (fixed1), label149, 72, 232);
  gtk_widget_set_size_request (label149, 41, 17);

  label147 = gtk_label_new (_("recepteur"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed1), label147, 8, 144);
  gtk_widget_set_size_request (label147, 104, 24);

  label145 = gtk_label_new (_("Id Message"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed1), label145, 336, 224);
  gtk_widget_set_size_request (label145, 120, 32);

  entry46 = gtk_entry_new ();
  gtk_widget_show (entry46);
  gtk_fixed_put (GTK_FIXED (fixed1), entry46, 440, 224);
  gtk_widget_set_size_request (entry46, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry46), 8226);

  textview3 = gtk_text_view_new ();
  gtk_widget_show (textview3);
  gtk_fixed_put (GTK_FIXED (fixed1), textview3, 176, 296);
  gtk_widget_set_size_request (textview3, 272, 80);

  button55 = gtk_button_new ();
  gtk_widget_show (button55);
  gtk_fixed_put (GTK_FIXED (fixed1), button55, 296, 400);
  gtk_widget_set_size_request (button55, 104, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button55), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox1), label6, FALSE, FALSE, 0);

  label150 = gtk_label_new ("");
  gtk_widget_show (label150);
  gtk_fixed_put (GTK_FIXED (fixed1), label150, 240, 440);
  gtk_widget_set_size_request (label150, 136, 24);

  combobox10 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox10);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox10, 144, 72);
  gtk_widget_set_size_request (combobox10, 104, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox10), _("Client"));

  combobox11 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox11);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox11, 128, 144);
  gtk_widget_set_size_request (combobox11, 120, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox11), _("Admin"));

  button58 = gtk_button_new_with_mnemonic (_("afficher"));
  gtk_widget_show (button58);
  gtk_fixed_put (GTK_FIXED (fixed1), button58, 400, 24);
  gtk_widget_set_size_request (button58, 76, 29);

  g_signal_connect ((gpointer) button55, "clicked",
                    G_CALLBACK (on_button55_clicked),
                    NULL);
  g_signal_connect ((gpointer) button58, "clicked",
                    G_CALLBACK (on_button58_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label146, "label146");
  GLADE_HOOKUP_OBJECT (window1, spinbutton31, "spinbutton31");
  GLADE_HOOKUP_OBJECT (window1, label148, "label148");
  GLADE_HOOKUP_OBJECT (window1, combobox12, "combobox12");
  GLADE_HOOKUP_OBJECT (window1, spinbutton32, "spinbutton32");
  GLADE_HOOKUP_OBJECT (window1, entry45, "entry45");
  GLADE_HOOKUP_OBJECT (window1, label149, "label149");
  GLADE_HOOKUP_OBJECT (window1, label147, "label147");
  GLADE_HOOKUP_OBJECT (window1, label145, "label145");
  GLADE_HOOKUP_OBJECT (window1, entry46, "entry46");
  GLADE_HOOKUP_OBJECT (window1, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (window1, button55, "button55");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label150, "label150");
  GLADE_HOOKUP_OBJECT (window1, combobox10, "combobox10");
  GLADE_HOOKUP_OBJECT (window1, combobox11, "combobox11");
  GLADE_HOOKUP_OBJECT (window1, button58, "button58");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *clist1;
  GtkWidget *label157;
  GtkWidget *label158;
  GtkWidget *label159;
  GtkWidget *label160;
  GtkWidget *label161;
  GtkWidget *button56;
  GtkWidget *label155;
  GtkWidget *fixed4;
  GtkWidget *entry50;
  GtkWidget *entry51;
  GtkWidget *entry52;
  GtkWidget *entry53;
  GtkWidget *textview4;
  GtkObject *spinbutton34_adj;
  GtkWidget *spinbutton34;
  GtkObject *spinbutton35_adj;
  GtkWidget *spinbutton35;
  GtkWidget *label162;
  GtkWidget *label166;
  GtkWidget *label163;
  GtkWidget *label164;
  GtkWidget *label165;
  GtkWidget *combobox13;
  GtkWidget *button59;
  GtkWidget *button61;
  GtkWidget *button60;
  GtkWidget *label156;
  GtkWidget *button57;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window2, 688, 500);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);
  gtk_widget_set_size_request (fixed2, 744, 391);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 48, 96);
  gtk_widget_set_size_request (notebook1, 600, 384);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  clist1 = gtk_clist_new (5);
  gtk_widget_show (clist1);
  gtk_fixed_put (GTK_FIXED (fixed3), clist1, 8, 56);
  gtk_widget_set_size_request (clist1, 500, 239);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 360);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  label157 = gtk_label_new (_("ID"));
  gtk_widget_show (label157);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label157);

  label158 = gtk_label_new (_("expiditeur"));
  gtk_widget_show (label158);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label158);

  label159 = gtk_label_new (_("recepteur"));
  gtk_widget_show (label159);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, label159);

  label160 = gtk_label_new (_("objet"));
  gtk_widget_show (label160);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, label160);

  label161 = gtk_label_new (_("date"));
  gtk_widget_show (label161);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, label161);

  button56 = gtk_button_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (button56);
  gtk_fixed_put (GTK_FIXED (fixed3), button56, 328, 16);
  gtk_widget_set_size_request (button56, 76, 29);

  label155 = gtk_label_new (_("affichage"));
  gtk_widget_show (label155);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label155);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);
  gtk_widget_set_size_request (fixed4, 120, -1);

  entry50 = gtk_entry_new ();
  gtk_widget_show (entry50);
  gtk_fixed_put (GTK_FIXED (fixed4), entry50, 328, 32);
  gtk_widget_set_size_request (entry50, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry50), 8226);

  entry51 = gtk_entry_new ();
  gtk_widget_show (entry51);
  gtk_fixed_put (GTK_FIXED (fixed4), entry51, 120, 72);
  gtk_widget_set_size_request (entry51, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry51), 8226);

  entry52 = gtk_entry_new ();
  gtk_widget_show (entry52);
  gtk_fixed_put (GTK_FIXED (fixed4), entry52, 120, 112);
  gtk_widget_set_size_request (entry52, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry52), 8226);

  entry53 = gtk_entry_new ();
  gtk_widget_show (entry53);
  gtk_fixed_put (GTK_FIXED (fixed4), entry53, 120, 160);
  gtk_widget_set_size_request (entry53, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry53), 8226);

  textview4 = gtk_text_view_new ();
  gtk_widget_show (textview4);
  gtk_fixed_put (GTK_FIXED (fixed4), textview4, 40, 224);
  gtk_widget_set_size_request (textview4, 512, 96);

  spinbutton34_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton34 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton34_adj), 1, 0);
  gtk_widget_show (spinbutton34);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton34, 312, 120);
  gtk_widget_set_size_request (spinbutton34, 60, 27);

  spinbutton35_adj = gtk_adjustment_new (1, 2019, 2100, 1, 10, 10);
  spinbutton35 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton35_adj), 1, 0);
  gtk_widget_show (spinbutton35);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton35, 768, 128);
  gtk_widget_set_size_request (spinbutton35, 60, 27);

  label162 = gtk_label_new (_("ID"));
  gtk_widget_show (label162);
  gtk_fixed_put (GTK_FIXED (fixed4), label162, 256, 40);
  gtk_widget_set_size_request (label162, 57, 17);

  label166 = gtk_label_new ("");
  gtk_widget_show (label166);
  gtk_fixed_put (GTK_FIXED (fixed4), label166, 328, 72);
  gtk_widget_set_size_request (label166, 168, 16);

  label163 = gtk_label_new (_("expiditeur"));
  gtk_widget_show (label163);
  gtk_fixed_put (GTK_FIXED (fixed4), label163, 32, 80);
  gtk_widget_set_size_request (label163, 80, 16);

  label164 = gtk_label_new (_("recepteur"));
  gtk_widget_show (label164);
  gtk_fixed_put (GTK_FIXED (fixed4), label164, 24, 120);
  gtk_widget_set_size_request (label164, 88, 16);

  label165 = gtk_label_new (_("objet"));
  gtk_widget_show (label165);
  gtk_fixed_put (GTK_FIXED (fixed4), label165, 32, 168);
  gtk_widget_set_size_request (label165, 80, 16);

  combobox13 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox13);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox13, 376, 120);
  gtk_widget_set_size_request (combobox13, 112, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Janvier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Fevrier"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Mars"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Avril"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Mai"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Juin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Juillet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Aout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Septembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Octobre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("Novembre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox13), _("D\303\251cembre"));

  button59 = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (button59);
  gtk_fixed_put (GTK_FIXED (fixed4), button59, 488, 64);
  gtk_widget_set_size_request (button59, 88, 32);

  button61 = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button61);
  gtk_fixed_put (GTK_FIXED (fixed4), button61, 352, 320);
  gtk_widget_set_size_request (button61, 72, 32);

  button60 = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (button60);
  gtk_fixed_put (GTK_FIXED (fixed4), button60, 112, 320);
  gtk_widget_set_size_request (button60, 88, 32);

  label156 = gtk_label_new (_("rechercher"));
  gtk_widget_show (label156);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label156);

  button57 = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button57);
  gtk_fixed_put (GTK_FIXED (fixed2), button57, 544, 88);
  gtk_widget_set_size_request (button57, 76, 29);

  g_signal_connect ((gpointer) button56, "clicked",
                    G_CALLBACK (on_button56_clicked),
                    NULL);
  g_signal_connect ((gpointer) button59, "clicked",
                    G_CALLBACK (on_button59_clicked),
                    NULL);
  g_signal_connect ((gpointer) button61, "activate",
                    G_CALLBACK (on_button61_activate),
                    NULL);
  g_signal_connect ((gpointer) button61, "clicked",
                    G_CALLBACK (on_button61_clicked),
                    NULL);
  g_signal_connect ((gpointer) button60, "clicked",
                    G_CALLBACK (on_button60_clicked),
                    NULL);
  g_signal_connect ((gpointer) button57, "clicked",
                    G_CALLBACK (on_button57_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, clist1, "clist1");
  GLADE_HOOKUP_OBJECT (window2, label157, "label157");
  GLADE_HOOKUP_OBJECT (window2, label158, "label158");
  GLADE_HOOKUP_OBJECT (window2, label159, "label159");
  GLADE_HOOKUP_OBJECT (window2, label160, "label160");
  GLADE_HOOKUP_OBJECT (window2, label161, "label161");
  GLADE_HOOKUP_OBJECT (window2, button56, "button56");
  GLADE_HOOKUP_OBJECT (window2, label155, "label155");
  GLADE_HOOKUP_OBJECT (window2, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window2, entry50, "entry50");
  GLADE_HOOKUP_OBJECT (window2, entry51, "entry51");
  GLADE_HOOKUP_OBJECT (window2, entry52, "entry52");
  GLADE_HOOKUP_OBJECT (window2, entry53, "entry53");
  GLADE_HOOKUP_OBJECT (window2, textview4, "textview4");
  GLADE_HOOKUP_OBJECT (window2, spinbutton34, "spinbutton34");
  GLADE_HOOKUP_OBJECT (window2, spinbutton35, "spinbutton35");
  GLADE_HOOKUP_OBJECT (window2, label162, "label162");
  GLADE_HOOKUP_OBJECT (window2, label166, "label166");
  GLADE_HOOKUP_OBJECT (window2, label163, "label163");
  GLADE_HOOKUP_OBJECT (window2, label164, "label164");
  GLADE_HOOKUP_OBJECT (window2, label165, "label165");
  GLADE_HOOKUP_OBJECT (window2, combobox13, "combobox13");
  GLADE_HOOKUP_OBJECT (window2, button59, "button59");
  GLADE_HOOKUP_OBJECT (window2, button61, "button61");
  GLADE_HOOKUP_OBJECT (window2, button60, "button60");
  GLADE_HOOKUP_OBJECT (window2, label156, "label156");
  GLADE_HOOKUP_OBJECT (window2, button57, "button57");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");

  return window3;
}

